<?php
array_push($this->myTypes, 'application/vnd.ms-excel');
array_push($this->myTypes, 'application/atom+xml');
array_push($this->myTypes, 'application/iges');
array_push($this->myTypes, 'application/javascript');
array_push($this->myTypes, 'application/dxf');
array_push($this->myTypes, 'application/mp4');
array_push($this->myTypes, 'application/iges');
array_push($this->myTypes, 'application/octet-stream');
array_push($this->myTypes, 'application/msword');
array_push($this->myTypes, 'application/pdf');
array_push($this->myTypes, 'application/postscript');
array_push($this->myTypes, 'application/mm');
array_push($this->myTypes, 'application/rtf');
array_push($this->myTypes, 'application/sgml');
array_push($this->myTypes, 'application/vnd.ms-excel');
array_push($this->myTypes, 'application/vnd.ms-powerpoint');
array_push($this->myTypes, 'application/xml');
array_push($this->myTypes, 'application/x-tar');
array_push($this->myTypes, 'application/zip');
array_push($this->myTypes, 'audio/basic');
array_push($this->myTypes, 'audio/mpeg');
array_push($this->myTypes, 'audio/mp4');
array_push($this->myTypes, 'audio/x-aiff');
array_push($this->myTypes, 'audio/x-wav');
array_push($this->myTypes, 'image/gif');
array_push($this->myTypes, 'image/jpeg');
array_push($this->myTypes, 'image/png');
array_push($this->myTypes, 'image/tiff');
array_push($this->myTypes, 'image/x-portable-bitmap');
array_push($this->myTypes, 'image/x-portable-graymap');
array_push($this->myTypes, 'image/x-portable-pixmap');
array_push($this->myTypes, 'multipart/x-zip');
array_push($this->myTypes, 'multipart/x-gzip');
array_push($this->myTypes, 'text/css');
array_push($this->myTypes, 'text/csv');
array_push($this->myTypes, 'text/html');
array_push($this->myTypes, 'text/plain');
array_push($this->myTypes, 'text/richtext');
array_push($this->myTypes, 'text/rtf');
array_push($this->myTypes, 'text/tab-separated-value');
array_push($this->myTypes, 'text/xml');
array_push($this->myTypes, 'video/h264');
array_push($this->myTypes, 'video/dv');
array_push($this->myTypes, 'video/mpeg');
array_push($this->myTypes, 'video/quicktime');
array_push($this->myTypes, 'video/msvideo');
array_push($this->myTypes, '');
?>